[package]
name = "amazons"
version = "0.1.0"
authors = ["Karl <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true

[dependencies]
bv = "0.11.0"
smallvec = "1.6.1"

termion = "1.5.3"