[package]
name = "amazons"
version = "0.1.0"
authors = ["Karl <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bv = "0.11.0"
rand = "0.7"